spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/trip;MODE=MYSQL
      username: ${DB_USERNAME}

  h2:
    console:
      enabled: true
  session:
    store-type: jdbc