name: how-about-trip-webservice

on:
  push:
    branches:
      - master
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew
        shell: bash

      - name: Build with Gradle
        run: backend/gradlew clean build
        shell: bash