name: how-about-trip-webservice

on:
  push:
    branches:
      - master
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up MySQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database: 'trip'
          mysql user: ${DB_USERNAME}
          mysql password: ${DB_PASSWORD}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash